### ISSUE TITLE
[Bug] Logging out does not work propetly

### ISSUE THREAD

**Issue by pcktm** [arogan-group/irc4osu#15]
After pressing "Logout" logging screen pops out for a split of a second and then it logs back in. Sometimes it causes weird behaviour like saying "Joined #english!" two times in a row or saying "Joined #polish!" after a few messages were sent and recived. And sorry for my retarded english.

**Comment by hallowatcher** [comment]
Known bug, fixed in e4ec2e2fba4801765b70e8149037f1838e4f7c4c & 1b831069316904cc966b8d1309e44883678b3d5b
