### ISSUE TITLE
Deprecation Warning [DEP0013]

### ISSUE THREAD

**Issue by TheMeq** [arogan-group/irc4osu#36]
(node:17232) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
  | writeOut | @ | internal/process/warning.js:28
  | output | @ | internal/process/warning.js:76
  | process.on | @ | internal/process/warning.js:107
  | emitOne | @ | events.js:115
  | emit | @ | events.js:210
  | (anonymous) | @ | internal/process/warning.js:81
  | _combinedTickCallback | @ | internal/process/next_tick.js:131
  | _tickCallback | @ | internal/process/next_tick.js:180

**Comment by TheMeq** [comment]
Issue is with Electron, not irc4osu!

**Comment by gamelaster** [comment]
Will update of electron solve this?

**Comment by TheMeq** [comment]
Please see Pull Request #43

**Comment by gamelaster** [comment]
Merged, let's close this. Thank you
