### ISSUE TITLE
Usernames in chat list contain underscores when they shouldn't

### ISSUE THREAD

**Issue by TheMeq** [arogan-group/irc4osu#39]
![irc4osu_2018-02-28_09-16-32](https://user-images.githubusercontent.com/7303969/36779555-49349d62-1c68-11e8-805e-9f4cb576794b.png)

These underscores should not exist within these usernames.

**Comment by TheMeq** [comment]
- Eat it - : https://osu.ppy.sh/u/-%20Eat%20it%20-
Rythm_Recon : http://osu.ppy.sh/u/Rythm%20Recon

**Comment by hallowatcher** [comment]
This is part of the IRC protocol, it fetches the names with an underscore

**Comment by TheMeq** [comment]
Not able to be fixed due to IRC protocol.
