### ISSUE TITLE
If message contains 2 links, it does not detect second link

### ISSUE THREAD

**Issue by TheMeq** [arogan-group/irc4osu#41]
this line for example: 
    `[http://osu.ppy.sh/s/596973 Himeringo - Yuudachi no Ribbon] has been revived from eternal slumber by [http://osu.ppy.sh/u/7480417 2-D -kun].`

comes out as
    `[12:11] BanchoBot: Himeringo - Yuudachi no Ribbon has been revived from eternal slumber by [http://osu.ppy.sh/u/7480417 2-D -kun].`

**Comment by TheMeq** [comment]
This only occurs after the commit that fixes #11 was applied.

**Comment by hallowatcher** [comment]
I knew there had to be a catch with your fix xD
Anyways, should I revert the PR until we fix this up?

**Comment by TheMeq** [comment]
Might be worth, I’m looking into it now :)

**Comment by TheMeq** [comment]
This has been fixed in latest commit.
