### ISSUE TITLE
Fix tab closing issue

### ISSUE THREAD

**Issue by hallowatcher** [arogan-group/irc4osu#6]
Whenever a tab gets closed, a blank page is displayed

**Comment by hallowatcher** [comment]
Context
![image](https://cloud.githubusercontent.com/assets/6265839/19854561/e457b6c0-9f6f-11e6-9bce-85d62d6e0497.png)

**Comment by gamelaster** [comment]
I have the associated array with channels what is bad, I need to change it (the code for select to the last tab is really long and ... scary)

**Comment by hallowatcher** [comment]
Fixed in f3c10506ca74b85603740e254ec4561129e68d8c
